[loggers]
keys=root, tac, tac_application, tac_infrastructure, tac_interface,
  librespot_ev, apscheduler, tac_os, tac_sound_device, tac_api,
  tac_display, utils_drawing, tac_controls, tac_domain, tac_mcp, 
  tac_mcp_buttons, tac_mcp_rotary_encoder, tac_keyboard_buttons, tac_event_bus, tac_mode_coordinator, tac_audio, 
  tac_hardware_input_handler, tac_scheduler, tac_system_service

[handlers]
keys=consoleHandler, lastResort

[formatters]
keys=simpleFormatter

[logger_root]
level=INFO
handlers=consoleHandler

[logger_tac]
level=NOTSET
qualname=tac
handlers=lastResort

[logger_tac_application]
level=DEBUG
qualname=tac.core.application
handlers=lastResort

[logger_tac_domain]
level=INFO
qualname=tac.core.domain
handlers=lastResort

[logger_tac_infrastructure]
level=NOTSET
qualname=tac.core.infrastructure
handlers=lastResort

[logger_tac_interface]
level=NOTSET
qualname=tac.core.interface
handlers=lastResort

[logger_tac_event_bus]
level=INFO
qualname=tac.core.infrastructure.event_bus
handlers=lastResort

[logger_tac_api]
level=INFO
qualname=tac.core.application.api
handlers=lastResort

[logger_tac_controls]
level=DEBUG
qualname=tac.core.application.controls
handlers=lastResort

[logger_tac_mode_coordinator]
level=INFO
qualname=tac.core.domain.mode_coordinator
handlers=lastResort

[logger_tac_hardware_input_handler]
level=INFO
qualname=tac.core.interface.hardware_input_handler
handlers=lastResort


[logger_tac_display]
level=INFO
qualname=tac.core.interface.display
handlers=lastResort

[logger_utils_drawing]
level=INFO
qualname=utils.drawing
handlers=lastResort

[logger_tac_audio]
level=INFO
qualname=tac.core.audio
handlers=lastResort

[logger_tac_os]
level=INFO
qualname=tac.os
handlers=lastResort

[logger_tac_sound_device]
level=INFO
qualname=tac.sound_device
handlers=lastResort

[logger_librespot_ev]
level=DEBUG
qualname=librespot_ev
handlers=lastResort

[logger_apscheduler]
level=CRITICAL
qualname=apscheduler.executors.default
handlers=lastResort

[logger_tac_mcp]
level=DEBUG
qualname=tac.core.mcp
handlers=lastResort

[logger_tac_mcp_buttons]
level=INFO
qualname=tac.core.mcp.buttons
handlers=lastResort

[logger_tac_mcp_rotary_encoder]
level=INFO
qualname=tac.core.mcp.rotary_encoder
handlers=lastResort

[logger_tac_keyboard_buttons]
level=INFO
qualname=tac.core.keyboard_buttons
handlers=lastResort

[logger_tac_scheduler]
level=NOTSET
qualname=tac.core.scheduler
handlers=lastResort

[logger_tac_system_service]
level=INFO
qualname=tac.core.application.system_service
handlers=lastResort

[handler_consoleHandler]
class=StreamHandler
formatter=simpleFormatter
args=(sys.stdout,)

[handler_lastResort]
class=NullHandler
level=NOTSET

[formatter_simpleFormatter]
format=%(name)s [%(levelname)s](%(threadName)s): %(message)s
