# /etc/raspotify/conf -- Arguments/configuration for librespot

# LIBRESPOT_QUIET=on
LIBRESPOT_DISABLE_AUDIO_CACHE=on
LIBRESPOT_DISABLE_CREDENTIAL_CACHE=on
LIBRESPOT_ENABLE_VOLUME_NORMALISATION=on
LIBRESPOT_NAME="the-alarm-clock"
LIBRESPOT_MIXER="alsa"
LIBRESPOT_ALSA_MIXER_DEVICE="hw:CARD=DigiAMP"
LIBRESPOT_ALSA_MIXER_CONTROL="Digital"
TMPDIR=/tmp
LIBRESPOT_SYSTEM_CACHE=/tmp

LIBRESPOT_ONEVENT="bash /srv/the-alarm-clock/app/rpi/onspotifyevent.sh"
